### ISSUE TITLE
c4l14 updates

### ISSUE THREAD

**Issue by thatandromeda** [code4lib/antiharassment-policy#34]
Will need to be updated with organizer contacts for the 2014 conference.  This includes replacing the line "For #c4l13, that would be Francis Kayiwa" and filling in all the stuff in brackets in the Sanctions area.

**Comment by phette23** [comment]
I think the CoC has been sufficiently genericized; I couldn't find any references to @kayiwa or C4L13. Someone want to double-check and then close this issue?

**Comment by escowles** [comment]
:+1:  -- all of the things that need to be customized each year are now in brackets.  They'll need to be updated each year, but we can close this issue.
