### ISSUE TITLE
Alter initial response level?

### ISSUE THREAD

**Issue by thatandromeda** [code4lib/antiharassment-policy#44]
The initial response level in our Code of Conduct is that the harassed should notify the offender to knock it off.  This seems like a great option right up until it isn't.  In particular...

* In cases of genuine misunderstanding or non-malicious cluelessness, sometimes things can be resolved this way and it really is the best way. But:
* It requires someone who may already be really upset to attempt, and maybe even pass, a diplomacy check.  That's hard! And it requires them to engage further with someone whose interactions are already distressing.  And it may require someone who's in a multiply-marginalized position to take on someone of higher social status and get them to admit they're doing social wrong.
* There are cases where this response level is actually unsafe.

I'd like to keep in the recommendation of resolving things amongst the parties where possible, but have language that allows for bypassing that when it's not a good idea.

Perhaps "please inform" -> "please consider informing"?  Or "please inform...if you are comfortable doing so"?

I'd also like to talk about the "if you see someone else being harassed". I think it is _very_ important that we recognize the role of third parties; yay! But whether someone feels harassed can be a tough judgment call from the outside, and white knighting is a concern here.

Maybe have a first paragraph aimed at the person who is being harassed, and a second aimed at third parties, to the effect of "If you see someone you believe is being harassed, thank you for watching out for your community! Please _do_ give them a chance to exit the situation gracefully; please _don't_ assume that they are in need of rescue. Best practice is to ask if they need help ("are you okay with this?" or "is this person bothering you?"), or to give them a chance to leave ("we're going to go do X, wanna come along?")"

I'm thinking about [this advice](http://everydayfeminism.com/2013/11/allies-to-women-at-parties/) here.

**Comment by anarchivist** [comment]
Closed by #47.
