### ISSUE TITLE
Crazy stalker

### ISSUE THREAD

**Issue by Detectivek** [code4lib/antiharassment-policy#55]
Yeah well I'm the victim and it needs to stop now

**Comment by anarchivist** [comment]
Hi there - I'm sorry to hear about this.  If your stalker is part of the Code4lib community, please let us know - we can provide you with a private contact method if you prefer. If you are looking for resources for support in this case, you might want to look at the following:

* [The Stalking Resource Center's **Help for Victims** page](https://victimsofcrime.org/our-programs/stalking-resource-center/help-for-victims), which includes a [stalking incident log document](http://www.victimsofcrime.org/docs/src/stalking-incident-log_pdf.pdf?sfvrsn=4) for recording information about instances.
* The Feminist Majority Foundation's page on [sexual harrassment hotlines and resources](http://www.feminist.org/911/harass.html) has a list of local resources that may be useful, even though the context is different.

**Comment by Detectivek** [comment]
That isn't going to help. He won't stop and I need actual proof that people actually understand

**Comment by Detectivek** [comment]
I never said it was anybody I want to hear but I need some help being able to get him away from me completely if you have help tonight I appreciate it

**Comment by Detectivek** [comment]
I don't want an apology I just want him out of my life and off my phone because he's breaking laws and he's sick and he's walking the streets and he doesn't even want me

**Comment by yo-bj** [comment]
I'm sorry that this has continued to be an issue. Again, we can provide you with a private contact method if this involves a person in the code4lib community. The resources that anarchivist provides can help, though another resource that could provide more immediate assistance is the [Crash Override Network](http://www.crashoverridenetwork.com/index.html); they have an confidential email address where you can request immediate assistance.
