### ISSUE TITLE
Apologise, mebbe?

### ISSUE THREAD

**Issue by abesottedphoenix** [code4lib/antiharassment-policy#8]
One of my problems with this policy is that it doesn't sound like us. I can only assume that this will be fixed. :) 

Can we add summat about offenders offering an apology up in here? I can only imagine that transgressors are like to feel bad and will want to do summat to clear things up.

**Comment by anarchivist** [comment]
This has been sitting with no discussion for three years. I propose to close this for now; we can reopen if there are remaining concerns.

**Comment by mjgiarlo** [comment]
:+1: to closing. Thanks for following up, @anarchivist
